#pragma once

#include "tetris.hpp"
#include <vector>

namespace minizero::env::moderntetris::engine {

/**
 * @brief Represents an action taken during placement search.
 */
enum class PlacementAction : std::uint8_t {
    NONE, // For initial state or root
    LEFT,
    RIGHT,
    LEFT_WALL,
    RIGHT_WALL,
    SOFT_DROP,
    SOFT_DROP_FLOOR,
    HARD_DROP,
    ROTATE_CW,
    ROTATE_CCW,
    ROTATE_180
};

/**
 * @brief Represents a unique locked placement outcome for a tetromino.
 *
 * Uniqueness of a placement is defined by its locked position on the board
 * (x, y), its orientation, and its resulting spin type. A piece placed at
 * the exact same identical position but with a different SpinType
 * (e.g. T-Spin vs Normal Drop) is considered a distinct placement rule outcome.
 */
struct PlacementSearchResult {
    std::int8_t lock_x;
    std::int8_t lock_y;
    std::uint8_t orientation;
    SpinType spin_type;

    /**
     * @brief The game state immediately after this placement is locked.
     *
     * This State is the exact engine state after `hardDrop()` is executed.
     * The piece has locked, `lines_cleared`, `attack`, `combo_count`, and
     * `spin_type` inside this state define the aftermath of the placement.
     *
     * CAUTION: The piece inside `final_state.current` has already advanced
     * to the next piece! This perfectly mimics a 1-step engine advancement.
     */
    State final_state;

    /**
     * @brief The sequence of actions from the initial state to the un-locked state
     * just before the locking hard drop. The implicit final action to reach `final_state`
     * is a hard drop.
     */
    std::vector<PlacementAction> path;
};

/**
 * @brief Brute-force searches all valid placements for the piece currently active
 * in the provided state.
 *
 * Uses Breadth-First Search (BFS) over all engine-valid moves (Left, Right, Soft Drop,
 * CW, CCW, 180) to explore every theoretically reachable (x, y, orientation, rotation_status)
 * spatial state. Extracts all unique `PlacementSearchResult` generated by dropping
 * and locking the piece from any of these intermediate spatial states.
 *
 * @param initial_state The game state from which the current piece starts moving.
 * @return A std::vector of all unique locked placements.
 */
std::vector<PlacementSearchResult> findPlacements(const State& initial_state);

// Symmetric pieces have distinct (x, y, orientation) tuples that occupy the SAME
// board cells; canonicalizePlacement collapses each onto one representative so a
// placement has a single label. The (dx, dy) corrections are derived from the 4x4
// piece tables (tetris.hpp `pieces[]`), where a cell at grid (col c, row r) maps
// to board (x + c, y + r):
//   * O: all four rotations occupy identical cells -> orientation 0, no shift.
//   * I/S/Z South(2): same cells as North(0) one bbox-row higher -> y + 1.
//   * I/S/Z West(3):  same cells as East(1)  one column to the right -> x - 1.
struct CanonicalPlacement {
    int lock_x;
    int lock_y;
    int orientation;
};

inline CanonicalPlacement canonicalizePlacement(PieceType piece, int lock_x, int lock_y, int orientation)
{
    switch (piece) {
        case PieceType::O:
            return {lock_x, lock_y, 0};
        case PieceType::I:
        case PieceType::S:
        case PieceType::Z:
            if (orientation == 2) { return {lock_x, lock_y + 1, 0}; } // South -> North
            if (orientation == 3) { return {lock_x - 1, lock_y, 1}; } // West  -> East
            return {lock_x, lock_y, orientation};                     // North / East unchanged
        default:
            return {lock_x, lock_y, orientation}; // L, J, T: all 4 distinct
    }
}

} // namespace minizero::env::moderntetris::engine
