#pragma once

#include "tetris.hpp"
#include <vector>

namespace minizero::env::moderntetris::engine {

/**
 * @brief Represents an action taken during placement search.
 */
enum class PlacementAction : std::uint8_t {
    NONE, // For initial state or root
    LEFT,
    RIGHT,
    LEFT_WALL,
    RIGHT_WALL,
    SOFT_DROP,
    SOFT_DROP_FLOOR,
    HARD_DROP,
    ROTATE_CW,
    ROTATE_CCW,
    ROTATE_180
};

/**
 * @brief Represents a unique locked placement outcome for a tetromino.
 *
 * Uniqueness of a placement is defined by its locked position on the board
 * (x, y), its orientation, and its resulting spin type. A piece placed at
 * the exact same identical position but with a different SpinType
 * (e.g. T-Spin vs Normal Drop) is considered a distinct placement rule outcome.
 */
struct PlacementSearchResult {
    std::int8_t lock_x;
    std::int8_t lock_y;
    std::uint8_t orientation;
    SpinType spin_type;

    /**
     * @brief The game state immediately after this placement is locked.
     *
     * This State is the exact engine state after `hardDrop()` is executed.
     * The piece has locked, `lines_cleared`, `attack`, `combo_count`, and
     * `spin_type` inside this state define the aftermath of the placement.
     *
     * CAUTION: The piece inside `final_state.current` has already advanced
     * to the next piece! This perfectly mimics a 1-step engine advancement.
     */
    State final_state;

    /**
     * @brief The sequence of actions from the initial state to the un-locked state
     * just before the locking hard drop. The implicit final action to reach `final_state`
     * is a hard drop.
     */
    std::vector<PlacementAction> path;
};

/**
 * @brief Brute-force searches all valid placements for the piece currently active
 * in the provided state.
 *
 * Uses Breadth-First Search (BFS) over all engine-valid moves (Left, Right, Soft Drop,
 * CW, CCW, 180) to explore every theoretically reachable (x, y, orientation, rotation_status)
 * spatial state. Extracts all unique `PlacementSearchResult` generated by dropping
 * and locking the piece from any of these intermediate spatial states.
 *
 * @param initial_state The game state from which the current piece starts moving.
 * @return A std::vector of all unique locked placements.
 */
std::vector<PlacementSearchResult> findPlacements(const State& initial_state);

} // namespace minizero::env::moderntetris::engine
